site_name: GHOSTBURN 2325 the Role-Playing Game
site_description: GHOSTBURN 2325 System Reference Document 1.0
site_author: sorites
docs_dir: docs/
theme:
  name: material
  palette:
  - scheme: default
    primary: indigo
    accent: pink
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode
  - scheme: slate
    primary: indigo
    accent: pink
    toggle:
      icon: material/brightness-4
      name: Switch to light mode
  features:
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.sections
  - navigation.expand
  - navigation.top
  - search.suggest
  - search.highlight
  - content.code.copy
  - toc.integrate
markdown_extensions:
- abbr
- admonition
- attr_list
- def_list
- footnotes
- md_in_html
- tables
- pymdownx.arithmatex:
    generic: true
- pymdownx.betterem
- pymdownx.caret
- pymdownx.details
- pymdownx.highlight:
    anchor_linenums: true
- pymdownx.inlinehilite
- pymdownx.keys
- pymdownx.mark
- pymdownx.smartsymbols
- pymdownx.superfences
- pymdownx.tabbed:
    alternate_style: true
- pymdownx.tasklist:
    custom_checkbox: true
- pymdownx.tilde
plugins:
- search
- autorefs
exclude_docs: 
  'Archive/
  assets/
  .obsidian/
  .git/
  '
extra_css:
- stylesheets/custom.css
nav:
- Home: index.md
- Characters:
  - Abilities and Ability Scores: Characters/Char_Abilities_and_Ability_Scores.md
  - Backgrounds: Characters/Char_Backgrounds.md
  - Burns and Hooks: Characters/Char_Burns_and_Hooks.md
  - Character Creation: Characters/Char_Character_Creation.md
  - NPCs: Characters/Char_NPCs.md
- Conditions:
  - Agony: Conditions/Condition_Agony.md
  - Ally: Conditions/Condition_Ally.md
  - Bewildered: Conditions/Condition_Bewildered.md
  - Bleeding: Conditions/Condition_Bleeding.md
  - Blinded: Conditions/Condition_Blinded.md
  - Break: Conditions/Condition_Break.md
  - Cognitive Impairment: Conditions/Condition_Cognitive_Impairment.md
  - Compliant: Conditions/Condition_Compliant.md
  - Concealment Partial: Conditions/Condition_Concealment_Partial.md
  - Concealment Total: Conditions/Condition_Concealment_Total.md
  - Confident: Conditions/Condition_Confident.md
  - Confused: Conditions/Condition_Confused.md
  - Cover Full: Conditions/Condition_Cover_Full.md
  - Cover Partial: Conditions/Condition_Cover_Partial.md
  - Critical Condition: Conditions/Condition_Critical_Condition.md
  - Deafened: Conditions/Condition_Deafened.md
  - Deaths Door: Conditions/Condition_Deaths_Door.md
  - Disfigured Major: Conditions/Condition_Disfigured_Major.md
  - Disfigured Minor: Conditions/Condition_Disfigured_Minor.md
  - Distracted: Conditions/Condition_Distracted.md
  - Drowning: Conditions/Condition_Drowning.md
  - Dying: Conditions/Condition_Dying.md
  - Emotional: Conditions/Condition_Emotional.md
  - Entertained: Conditions/Condition_Entertained.md
  - Fine Motor Impairment: Conditions/Condition_Fine_Motor_Impairment.md
  - Foggy: Conditions/Condition_Foggy.md
  - Healthy: Conditions/Condition_Healthy.md
  - Hearing Impairment: Conditions/Condition_Hearing_Impairment.md
  - Hidden: Conditions/Condition_Hidden.md
  - Immobilized: Conditions/Condition_Immobilized.md
  - Incapable: Conditions/Condition_Incapable.md
  - Inspired: Conditions/Condition_Inspired.md
  - Jammed: Conditions/Condition_Jammed.md
  - Life Threatening: Conditions/Condition_Life_Threatening.md
  - Mouth Breather: Conditions/Condition_Mouth_Breather.md
  - Movement Impaired: Conditions/Condition_Movement_Impaired.md
  - Movement Restricted: Conditions/Condition_Movement_Restricted.md
  - Mute: Conditions/Condition_Mute.md
  - Off Balance: Conditions/Condition_Off_Balance.md
  - Off Guard: Conditions/Condition_Off_Guard.md
  - Prone: Conditions/Condition_Prone.md
  - Raining: Conditions/Condition_Raining.md
  - Recovering: Conditions/Condition_Recovering.md
  - Restrained: Conditions/Condition_Restrained.md
  - Servile: Conditions/Condition_Servile.md
  - Severely Wounded: Conditions/Condition_Severely_Wounded.md
  - Shaken: Conditions/Condition_Shaken.md
  - Speech Impairment: Conditions/Condition_Speech_Impairment.md
  - Stabilized: Conditions/Condition_Stabilized.md
  - Stress: Conditions/Condition_Stress.md
  - Stunned: Conditions/Condition_Stunned.md
  - Suffocating: Conditions/Condition_Suffocating.md
  - Suppressed: Conditions/Condition_Suppressed.md
  - Suspicous: Conditions/Condition_Suspicous.md
  - Traumatized: Conditions/Condition_Traumatized.md
  - Unaware: Conditions/Condition_Unaware.md
  - Unconscious: Conditions/Condition_Unconscious.md
  - Undetected: Conditions/Condition_Undetected.md
  - Unresponsive: Conditions/Condition_Unresponsive.md
  - Vision Impairment: Conditions/Condition_Vision_Impairment.md
  - Windy: Conditions/Condition_Windy.md
  - Wounded: Conditions/Condition_Wounded.md
- Cybernetic Augmentations:
  - Cybernetic Augmentations: Cybernetic_Augmentations/Aug_Cybernetic_Augmentations.md
- Gear:
  - Damage Array: Gear/Gear_Damage_Array.md
  - Clearview: Gear/Gear_Clearview.md
  - Folding Stock: Gear/Gear_Folding_Stock.md
  - Gas Vents: Gear/Gear_Gas_Vents.md
  - Gunlink Grip: Gear/Gear_Gunlink_Grip.md
  - Laser Sight: Gear/Gear_Laser_Sight.md
  - Night Vision: Gear/Gear_Night_Vision.md
  - Scope: Gear/Gear_Scope.md
  - Silencer: Gear/Gear_Silencer.md
  - Thermal Imaging: Gear/Gear_Thermal_Imaging.md
  - Underbarrel Flashlight: Gear/Gear_Underbarrel_Flashlight.md
- Health and Healing:
  - Health Condition Effects: Health_and_Healing/HaH_Health_Condition_Effects.md
  - Hit Points and Conditions: Health_and_Healing/HaH_Hit_Points_and_Conditions.md
  - Stabilization DL: Health_and_Healing/HaH_Stabilization_DL.md
  - Sustaining an Injury: Health_and_Healing/HaH_Sustaining_an_Injury.md
- Keywords:
  - Absolute Damage: Keywords/Keyword_Absolute_Damage.md
  - Admin: Keywords/Keyword_Admin.md
  - Advanced Supplies: Keywords/Keyword_Advanced_Supplies.md
  - Armor: Keywords/Keyword_Armor.md
  - Attack: Keywords/Keyword_Attack.md
  - Attitude: Keywords/Keyword_Attitude.md
  - Auditory: Keywords/Keyword_Auditory.md
  - Aug Bonus: Keywords/Keyword_Aug_Bonus.md
  - Basic: Keywords/Keyword_Basic.md
  - Bladed: Keywords/Keyword_Bladed.md
  - Blunt Force: Keywords/Keyword_Blunt_Force.md
  - Close: Keywords/Keyword_Close.md
  - Concealable: Keywords/Keyword_Concealable.md
  - Concentrate: Keywords/Keyword_Concentrate.md
  - Condition: Keywords/Keyword_Condition.md
  - Contact: Keywords/Keyword_Contact.md
  - Control Deck: Keywords/Keyword_Control_Deck.md
  - Core Trick: Keywords/Keyword_Core_Trick.md
  - Counterattack: Keywords/Keyword_Counterattack.md
  - Crashes: Keywords/Keyword_Crashes.md
  - Cyber Rig: Keywords/Keyword_Cyber_Rig.md
  - Damage Array: Keywords/Keyword_Damage_Array.md
  - Datajack: Keywords/Keyword_Datajack.md
  - Disabled: Keywords/Keyword_Disabled.md
  - Downgraded: Keywords/Keyword_Downgraded.md
  - Drone: Keywords/Keyword_Drone.md
  - Enabled: Keywords/Keyword_Enabled.md
  - Far: Keywords/Keyword_Far.md
  - Fine Control: Keywords/Keyword_Fine_Control.md
  - Firearm: Keywords/Keyword_Firearm.md
  - Fly: Keywords/Keyword_Fly.md
  - Fort: Keywords/Keyword_Fort.md
  - Friendly: Keywords/Keyword_Friendly.md
  - Gear Bonus: Keywords/Keyword_Gear_Bonus.md
  - Gift: Keywords/Keyword_Gift.md
  - Group: Keywords/Keyword_Group.md
  - Gun: Keywords/Keyword_Gun.md
  - Handling: Keywords/Keyword_Handling.md
  - Heavy Arms: Keywords/Keyword_Heavy_Arms.md
  - High Speed: Keywords/Keyword_High_Speed.md
  - Hostile: Keywords/Keyword_Hostile.md
  - Improvised Trick: Keywords/Keyword_Improvised_Trick.md
  - Language: Keywords/Keyword_Language.md
  - Light Arms: Keywords/Keyword_Light_Arms.md
  - Location: Keywords/Keyword_Location.md
  - Low Speed: Keywords/Keyword_Low_Speed.md
  - Luck Bonus: Keywords/Keyword_Luck_Bonus.md
  - Lucky: Keywords/Keyword_Lucky.md
  - Manipulator Arm: Keywords/Keyword_Manipulator_Arm.md
  - Maximum Damage: Keywords/Keyword_Maximum_Damage.md
  - Melee: Keywords/Keyword_Melee.md
  - Minimum Damage: Keywords/Keyword_Minimum_Damage.md
  - Moderate Speed: Keywords/Keyword_Moderate_Speed.md
  - Move: Keywords/Keyword_Move.md
  - Nearby: Keywords/Keyword_Nearby.md
  - Neutral: Keywords/Keyword_Neutral.md
  - Normal Damage: Keywords/Keyword_Normal_Damage.md
  - One Hand: Keywords/Keyword_One_Hand.md
  - Operator: Keywords/Keyword_Operator.md
  - Opposed: Keywords/Keyword_Opposed.md
  - Optimal Range: Keywords/Keyword_Optimal_Range.md
  - Physical: Keywords/Keyword_Physical.md
  - Range: Keywords/Keyword_Range.md
  - Reaction: Keywords/Keyword_Reaction.md
  - Recoil: Keywords/Keyword_Recoil.md
  - Reduced: Keywords/Keyword_Reduced.md
  - Secret: Keywords/Keyword_Secret.md
  - Security: Keywords/Keyword_Security.md
  - Security Alert: Keywords/Keyword_Security_Alert.md
  - Signature Trick: Keywords/Keyword_Signature_Trick.md
  - Skill Bonus: Keywords/Keyword_Skill_Bonus.md
  - Small Item: Keywords/Keyword_Small_Item.md
  - Social: Keywords/Keyword_Social.md
  - Spray: Keywords/Keyword_Spray.md
  - Spread: Keywords/Keyword_Spread.md
  - Stability: Keywords/Keyword_Stability.md
  - Stabilization DL: Keywords/Keyword_Stabilization_DL.md
  - Supplies: Keywords/Keyword_Supplies.md
  - Surgical Procedure: Keywords/Keyword_Surgical_Procedure.md
  - Temporary: Keywords/Keyword_Temporary.md
  - Threat: Keywords/Keyword_Threat.md
  - Tools: Keywords/Keyword_Tools.md
  - Trick: Keywords/Keyword_Trick.md
  - Two Handed Grip: Keywords/Keyword_Two_Handed_Grip.md
  - Two Hands: Keywords/Keyword_Two_Hands.md
  - Unarmed Strike: Keywords/Keyword_Unarmed_Strike.md
  - Upgraded: Keywords/Keyword_Upgraded.md
  - Vehicle: Keywords/Keyword_Vehicle.md
  - Vicinity: Keywords/Keyword_Vicinity.md
  - Visible: Keywords/Keyword_Visible.md
  - Visual: Keywords/Keyword_Visual.md
  - Vocal: Keywords/Keyword_Vocal.md
  - Weapon Group: Keywords/Keyword_Weapon_Group.md
  - Weapon Types: Keywords/Keyword_Weapon_Types.md
  - Wireless: Keywords/Keyword_Wireless.md
  - Wits: Keywords/Keyword_Wits.md
- Making a Roll:
  - 2d10 Probability Tables: Making_a_Roll/MaR_2d10_Probability_Tables.md
  - Adjusting the Difficulty Level: Making_a_Roll/MaR_Adjusting_the_Difficulty_Level.md
  - Difficulty Level: Making_a_Roll/MaR_Difficulty_Level.md
  - End of the Action: Making_a_Roll/MaR_End_of_the_Action.md
  - Luck Points: Making_a_Roll/MaR_Luck_Points.md
  - Making a Roll: Making_a_Roll/MaR_Making_a_Roll.md
  - Outcomes: Making_a_Roll/MaR_Outcomes.md
  - Roll 2d10: Making_a_Roll/MaR_Roll_2d10.md
  - When to Roll: Making_a_Roll/MaR_When_to_Roll.md
- Skills and Tricks:
  - Skill Presence Intimidate: Skills_and_Tricks/SaT_Skill_Presence_Intimidate.md
  - Skill Presence Persuade: Skills_and_Tricks/SaT_Skill_Presence_Persuade.md
  - Skills and Tricks: Skills_and_Tricks/SaT_Skills_and_Tricks.md
  - Skills and Tricks List: Skills_and_Tricks/SaT_Skills_and_Tricks_List.md
  - Athletics:
    - Athletic Move [Core]: Skills_and_Tricks/Trick_Athletics_Core_Athletic_Move.md
    - Catch [Core]: Skills_and_Tricks/Trick_Athletics_Core_Catch.md
    - Sprint [Core]: Skills_and_Tricks/Trick_Athletics_Core_Sprint.md
    - Throw [Core]: Skills_and_Tricks/Trick_Athletics_Core_Throw.md
    - Acrobatic Stunt [Signature]: Skills_and_Tricks/Trick_Athletics_Acrobatic_Stunt.md    
  - Brawl Core Forced Move: Skills_and_Tricks/Trick_Brawl_Core_Forced_Move.md
  - Brawl Core Grapple: Skills_and_Tricks/Trick_Brawl_Core_Grapple.md
  - Brawl Core Unarmed Strike: Skills_and_Tricks/Trick_Brawl_Core_Unarmed_Strike.md
  - Brawl Silent Takedown: Skills_and_Tricks/Trick_Brawl_Silent_Takedown.md
  - Culture Core City Culture: Skills_and_Tricks/Trick_Culture_Core_City_Culture.md
  - Culture Corporate Culture: Skills_and_Tricks/Trick_Culture_Corporate_Culture.md
  - Culture Milsec Culture: Skills_and_Tricks/Trick_Culture_Milsec_Culture.md
  - Culture Street Culture: Skills_and_Tricks/Trick_Culture_Street_Culture.md
  - Culture Underworld Culture: Skills_and_Tricks/Trick_Culture_Underworld_Culture.md
  - Deception Core Bluff: Skills_and_Tricks/Trick_Deception_Core_Bluff.md
  - Deception Core Misdirect: Skills_and_Tricks/Trick_Deception_Core_Misdirect.md
  - Deception Disguise: Skills_and_Tricks/Trick_Deception_Disguise.md
  - Deception Forgery: Skills_and_Tricks/Trick_Deception_Forgery.md
  - Deception Impersonate: Skills_and_Tricks/Trick_Deception_Impersonate.md
  - Drive Core Avoid Crash: Skills_and_Tricks/Trick_Drive_Core_Avoid_Crash.md
  - Drive Core Chase: Skills_and_Tricks/Trick_Drive_Core_Chase.md
  - Drive Core Escape: Skills_and_Tricks/Trick_Drive_Core_Escape.md
  - Drive Core Sideswipe: Skills_and_Tricks/Trick_Drive_Core_Sideswipe.md
  - Drive Driving Stunt: Skills_and_Tricks/Trick_Drive_Driving_Stunt.md
  - Drive Pit Maneuver: Skills_and_Tricks/Trick_Drive_Pit_Maneuver.md
  - Firearms Core Burst Fire: Skills_and_Tricks/Trick_Firearms_Core_Burst_Fire.md
  - Firearms Core Full Auto: Skills_and_Tricks/Trick_Firearms_Core_Full_Auto.md
  - Firearms Core Single Shot: Skills_and_Tricks/Trick_Firearms_Core_Single_Shot.md
  - Firearms Crippling Shot: Skills_and_Tricks/Trick_Firearms_Crippling_Shot.md
  - Firearms Dual Shot: Skills_and_Tricks/Trick_Firearms_Dual_Shot.md
  - Hacking Core Disable Device: Skills_and_Tricks/Trick_Hacking_Core_Disable_Device.md
  - Hacking Cybernetic Hack: Skills_and_Tricks/Trick_Hacking_Cybernetic_Hack.md
  - Hacking Droptrip: Skills_and_Tricks/Trick_Hacking_Droptrip.md
  - Hacking Street Hack: Skills_and_Tricks/Trick_Hacking_Street_Hack.md
  - Insight Core Read Person: Skills_and_Tricks/Trick_Insight_Core_Read_Person.md
  - Insight Core Sense Lies: Skills_and_Tricks/Trick_Insight_Core_Sense_Lies.md
  - Insight Core Size Up Opponent: Skills_and_Tricks/Trick_Insight_Core_Size_Up_Opponent.md
  - Insight Dodge: Skills_and_Tricks/Trick_Insight_Dodge.md
  - Intimidate Core Coerce: Skills_and_Tricks/Trick_Intimidate_Core_Coerce.md
  - Intimidate Core Mock: Skills_and_Tricks/Trick_Intimidate_Core_Mock.md
  - Intimidate Frighten: Skills_and_Tricks/Trick_Intimidate_Frighten.md
  - Intimidate Shakedown: Skills_and_Tricks/Trick_Intimidate_Shakedown.md
  - Intimidate Shred: Skills_and_Tricks/Trick_Intimidate_Shred.md
  - Medicine Core First Aid: Skills_and_Tricks/Trick_Medicine_Core_First_Aid.md
  - Medicine Core Medical Assessment: Skills_and_Tricks/Trick_Medicine_Core_Medical_Assessment.md
  - Medicine Cybernetic Installation: Skills_and_Tricks/Trick_Medicine_Cybernetic_Installation.md
  - Medicine Surgery: Skills_and_Tricks/Trick_Medicine_Surgery.md
  - Melee Core Melee Strike: Skills_and_Tricks/Trick_Melee_Core_Melee_Strike.md
  - Melee Dazzling Strike: Skills_and_Tricks/Trick_Melee_Dazzling_Strike.md
  - Melee Finishing Move: Skills_and_Tricks/Trick_Melee_Finishing_Move.md
  - Melee Leaping Strike: Skills_and_Tricks/Trick_Melee_Leaping_Strike.md
  - Perception Core Search: Skills_and_Tricks/Trick_Perception_Core_Search.md
  - Perception Dead Eye: Skills_and_Tricks/Trick_Perception_Dead_Eye.md
  - Perception Overwatch: Skills_and_Tricks/Trick_Perception_Overwatch.md
  - Perception Read Lips: Skills_and_Tricks/Trick_Perception_Read_Lips.md
  - Persuade Captivate: Skills_and_Tricks/Trick_Persuade_Captivate.md
  - Persuade Core Convince: Skills_and_Tricks/Trick_Persuade_Core_Convince.md
  - Persuade Core Haggle: Skills_and_Tricks/Trick_Persuade_Core_Haggle.md
  - Persuade Entertain: Skills_and_Tricks/Trick_Persuade_Entertain.md
  - Piloting Core Deploy Payload: Skills_and_Tricks/Trick_Piloting_Core_Deploy_Payload.md
  - Piloting Core Drone Recon: Skills_and_Tricks/Trick_Piloting_Core_Drone_Recon.md
  - Piloting Initiate Countermeasures: Skills_and_Tricks/Trick_Piloting_Initiate_Countermeasures.md
  - Piloting Manipulate Object: Skills_and_Tricks/Trick_Piloting_Manipulate_Object.md
  - Piloting Strafing Run: Skills_and_Tricks/Trick_Piloting_Strafing_Run.md
  - Stealth Close Up Magic: Skills_and_Tricks/Trick_Stealth_Close_Up_Magic.md
  - Stealth Core Sneak: Skills_and_Tricks/Trick_Stealth_Core_Sneak.md
  - Stealth Disappear: Skills_and_Tricks/Trick_Stealth_Disappear.md
  - Stealth Pickpocket: Skills_and_Tricks/Trick_Stealth_Pickpocket.md
  - Stealth Shadow Target: Skills_and_Tricks/Trick_Stealth_Shadow_Target.md
- Turns:
  - Round Robin the Flow of the Game: Turns/Turns_Round_Robin_the_Flow_of_the_Game.md
  - Turn Etiquette: Turns/Turns_Turn_Etiquette.md
  - Turn Length: Turns/Turns_Turn_Length.md
  - Turn Order: Turns/Turns_Turn_Order.md
  - Types of Turns: Turns/Turns_Types_of_Turns.md
  - Your Turn: Turns/Turns_Your_Turn.md
