site_name: GHOSTBURN 2325 the Role-Playing Game
site_description: GHOSTBURN 2325 System Reference Document 1.0
site_author: Justin Smith
docs_dir: docs
theme:
  name: material
  palette:
  - scheme: default
    primary: indigo
    accent: indigo
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode
  - scheme: slate
    primary: indigo
    accent: indigo
    toggle:
      icon: material/brightness-4
      name: Switch to light mode
  features:
  - navigation.tabs
  - navigation.sections
  - navigation.expand
  - navigation.top
  - search.suggest
  - search.highlight
  - content.code.copy
markdown_extensions:
- abbr
- admonition
- attr_list
- def_list
- footnotes
- md_in_html
- tables
- toc:
    permalink: true
- pymdownx.arithmatex:
    generic: true
- pymdownx.betterem
- pymdownx.caret
- pymdownx.details
- pymdownx.highlight:
    anchor_linenums: true
- pymdownx.inlinehilite
- pymdownx.keys
- pymdownx.mark
- pymdownx.smartsymbols
- pymdownx.superfences
- pymdownx.tabbed:
    alternate_style: true
- pymdownx.tasklist:
    custom_checkbox: true
- pymdownx.tilde
plugins:
- search
exclude_docs: 'Archive/

  assets/

  .obsidian/

  .git/

  '
extra_css:
- stylesheets/custom.css
nav:
- Characters:
  - Abilities_and_Ability_Scores: Characters\Abilities_and_Ability_Scores.md
  - Backgrounds: Characters\Backgrounds.md
  - Burns_and_Hooks: Characters\Burns_and_Hooks.md
  - Character_Creation: Characters\Character_Creation.md
  - NPCs: Characters\NPCs.md
- Conditions:
  - Condition_Agony: Conditions\Condition_Agony.md
  - Condition_Ally: Conditions\Condition_Ally.md
  - Condition_Bewildered: Conditions\Condition_Bewildered.md
  - Condition_Bleeding: Conditions\Condition_Bleeding.md
  - Condition_Blinded: Conditions\Condition_Blinded.md
  - Condition_Break: Conditions\Condition_Break.md
  - Condition_Cognitive_Impairment: Conditions\Condition_Cognitive_Impairment.md
  - Condition_Compliant: Conditions\Condition_Compliant.md
  - Condition_Concealment_Partial: Conditions\Condition_Concealment_Partial.md
  - Condition_Concealment_Total: Conditions\Condition_Concealment_Total.md
  - Condition_Confident: Conditions\Condition_Confident.md
  - Condition_Confused: Conditions\Condition_Confused.md
  - Condition_Cover_Full: Conditions\Condition_Cover_Full.md
  - Condition_Cover_Partial: Conditions\Condition_Cover_Partial.md
  - Condition_Critical_Condition: Conditions\Condition_Critical_Condition.md
  - Condition_Deafened: Conditions\Condition_Deafened.md
  - Condition_Deaths_Door: Conditions\Condition_Deaths_Door.md
  - Condition_Disfigured_Major: Conditions\Condition_Disfigured_Major.md
  - Condition_Disfigured_Minor: Conditions\Condition_Disfigured_Minor.md
  - Condition_Distracted: Conditions\Condition_Distracted.md
  - Condition_Drowning: Conditions\Condition_Drowning.md
  - Condition_Dying: Conditions\Condition_Dying.md
  - Condition_Emotional: Conditions\Condition_Emotional.md
  - Condition_Entertained: Conditions\Condition_Entertained.md
  - Condition_Fine_Motor_Impairment: Conditions\Condition_Fine_Motor_Impairment.md
  - Condition_Foggy: Conditions\Condition_Foggy.md
  - Condition_Healthy: Conditions\Condition_Healthy.md
  - Condition_Hearing_Impairment: Conditions\Condition_Hearing_Impairment.md
  - Condition_Hidden: Conditions\Condition_Hidden.md
  - Condition_Immobilized: Conditions\Condition_Immobilized.md
  - Condition_Incapable: Conditions\Condition_Incapable.md
  - Condition_Inspired: Conditions\Condition_Inspired.md
  - Condition_Jammed: Conditions\Condition_Jammed.md
  - Condition_Life_Threatening: Conditions\Condition_Life_Threatening.md
  - Condition_Mouth_Breather: Conditions\Condition_Mouth_Breather.md
  - Condition_Movement_Impaired: Conditions\Condition_Movement_Impaired.md
  - Condition_Movement_Restricted: Conditions\Condition_Movement_Restricted.md
  - Condition_Mute: Conditions\Condition_Mute.md
  - Condition_Off_Balance: Conditions\Condition_Off_Balance.md
  - Condition_Off_Guard: Conditions\Condition_Off_Guard.md
  - Condition_Prone: Conditions\Condition_Prone.md
  - Condition_Raining: Conditions\Condition_Raining.md
  - Condition_Recovering: Conditions\Condition_Recovering.md
  - Condition_Restrained: Conditions\Condition_Restrained.md
  - Condition_Servile: Conditions\Condition_Servile.md
  - Condition_Severely_Wounded: Conditions\Condition_Severely_Wounded.md
  - Condition_Shaken: Conditions\Condition_Shaken.md
  - Condition_Speech_Impairment: Conditions\Condition_Speech_Impairment.md
  - Condition_Stabilized: Conditions\Condition_Stabilized.md
  - Condition_Stress: Conditions\Condition_Stress.md
  - Condition_Stunned: Conditions\Condition_Stunned.md
  - Condition_Suffocating: Conditions\Condition_Suffocating.md
  - Condition_Suppressed: Conditions\Condition_Suppressed.md
  - Condition_Suspicous: Conditions\Condition_Suspicous.md
  - Condition_Traumatized: Conditions\Condition_Traumatized.md
  - Condition_Unaware: Conditions\Condition_Unaware.md
  - Condition_Unconscious: Conditions\Condition_Unconscious.md
  - Condition_Undetected: Conditions\Condition_Undetected.md
  - Condition_Unresponsive: Conditions\Condition_Unresponsive.md
  - Condition_Vision_Impairment: Conditions\Condition_Vision_Impairment.md
  - Condition_Windy: Conditions\Condition_Windy.md
  - Condition_Wounded: Conditions\Condition_Wounded.md
- Cybernetic_Augmentations:
  - Cybernetic Augmentations: Cybernetic_Augmentations\Cybernetic_Augmentations.md
- Gear:
  - Damage_Array: Gear\Damage_Array.md
  - Gear_Clearview: Gear\Gear_Clearview.md
  - Gear_Folding_Stock: Gear\Gear_Folding_Stock.md
  - Gear_Gas_Vents: Gear\Gear_Gas_Vents.md
  - Gear_Gunlink_Grip: Gear\Gear_Gunlink_Grip.md
  - Gear_Laser_Sight: Gear\Gear_Laser_Sight.md
  - Gear_Night_Vision: Gear\Gear_Night_Vision.md
  - Gear_Scope: Gear\Gear_Scope.md
  - Gear_Silencer: Gear\Gear_Silencer.md
  - Gear_Thermal_Imaging: Gear\Gear_Thermal_Imaging.md
  - Gear_Underbarrel_Flashlight: Gear\Gear_Underbarrel_Flashlight.md
- Health_and_Healing:
  - Health_Condition_Effects: Health_and_Healing\Health_Condition_Effects.md
  - Hit_Points_and_Conditions: Health_and_Healing\Hit_Points_and_Conditions.md
  - Stabilization_DL: Health_and_Healing\Stabilization_DL.md
  - Sustaining_an_Injury: Health_and_Healing\Sustaining_an_Injury.md
- Keywords:
  - Keyword_Absolute_Damage: Keywords\Keyword_Absolute_Damage.md
  - Keyword_Admin: Keywords\Keyword_Admin.md
  - Keyword_Advanced_Supplies: Keywords\Keyword_Advanced_Supplies.md
  - Keyword_Armor: Keywords\Keyword_Armor.md
  - Keyword_Attack: Keywords\Keyword_Attack.md
  - Keyword_Attitude: Keywords\Keyword_Attitude.md
  - Keyword_Auditory: Keywords\Keyword_Auditory.md
  - Keyword_Aug_Bonus: Keywords\Keyword_Aug_Bonus.md
  - Keyword_Basic: Keywords\Keyword_Basic.md
  - Keyword_Bladed: Keywords\Keyword_Bladed.md
  - Keyword_Blunt_Force: Keywords\Keyword_Blunt_Force.md
  - Keyword_Close: Keywords\Keyword_Close.md
  - Keyword_Concealable: Keywords\Keyword_Concealable.md
  - Keyword_Concentrate: Keywords\Keyword_Concentrate.md
  - Keyword_Condition: Keywords\Keyword_Condition.md
  - Keyword_Contact: Keywords\Keyword_Contact.md
  - Keyword_Control_Deck: Keywords\Keyword_Control_Deck.md
  - Keyword_Core_Trick: Keywords\Keyword_Core_Trick.md
  - Keyword_Counterattack: Keywords\Keyword_Counterattack.md
  - Keyword_Crashes: Keywords\Keyword_Crashes.md
  - Keyword_Cyber_Rig: Keywords\Keyword_Cyber_Rig.md
  - Keyword_Damage_Array: Keywords\Keyword_Damage_Array.md
  - Keyword_Datajack: Keywords\Keyword_Datajack.md
  - Keyword_Disabled: Keywords\Keyword_Disabled.md
  - Keyword_Downgraded: Keywords\Keyword_Downgraded.md
  - Keyword_Drone: Keywords\Keyword_Drone.md
  - Keyword_Enabled: Keywords\Keyword_Enabled.md
  - Keyword_Far: Keywords\Keyword_Far.md
  - Keyword_Fine_Control: Keywords\Keyword_Fine_Control.md
  - Keyword_Firearm: Keywords\Keyword_Firearm.md
  - Keyword_Fly: Keywords\Keyword_Fly.md
  - Keyword_Fort: Keywords\Keyword_Fort.md
  - Keyword_Friendly: Keywords\Keyword_Friendly.md
  - Keyword_Gear_Bonus: Keywords\Keyword_Gear_Bonus.md
  - Keyword_Gift: Keywords\Keyword_Gift.md
  - Keyword_Group: Keywords\Keyword_Group.md
  - Keyword_Gun: Keywords\Keyword_Gun.md
  - Keyword_Handling: Keywords\Keyword_Handling.md
  - Keyword_Heavy_Arms: Keywords\Keyword_Heavy_Arms.md
  - Keyword_High_Speed: Keywords\Keyword_High_Speed.md
  - Keyword_Hostile: Keywords\Keyword_Hostile.md
  - Keyword_Improvised_Trick: Keywords\Keyword_Improvised_Trick.md
  - Keyword_Language: Keywords\Keyword_Language.md
  - Keyword_Light_Arms: Keywords\Keyword_Light_Arms.md
  - Keyword_Location: Keywords\Keyword_Location.md
  - Keyword_Low_Speed: Keywords\Keyword_Low_Speed.md
  - Keyword_Luck_Bonus: Keywords\Keyword_Luck_Bonus.md
  - Keyword_Lucky: Keywords\Keyword_Lucky.md
  - Keyword_Manipulator_Arm: Keywords\Keyword_Manipulator_Arm.md
  - Keyword_Maximum_Damage: Keywords\Keyword_Maximum_Damage.md
  - Keyword_Melee: Keywords\Keyword_Melee.md
  - Keyword_Minimum_Damage: Keywords\Keyword_Minimum_Damage.md
  - Keyword_Moderate_Speed: Keywords\Keyword_Moderate_Speed.md
  - Keyword_Move: Keywords\Keyword_Move.md
  - Keyword_Nearby: Keywords\Keyword_Nearby.md
  - Keyword_Neutral: Keywords\Keyword_Neutral.md
  - Keyword_Normal_Damage: Keywords\Keyword_Normal_Damage.md
  - Keyword_One_Hand: Keywords\Keyword_One_Hand.md
  - Keyword_Operator: Keywords\Keyword_Operator.md
  - Keyword_Opposed: Keywords\Keyword_Opposed.md
  - Keyword_Optimal_Range: Keywords\Keyword_Optimal_Range.md
  - Keyword_Physical: Keywords\Keyword_Physical.md
  - Keyword_Range: Keywords\Keyword_Range.md
  - Keyword_Reaction: Keywords\Keyword_Reaction.md
  - Keyword_Recoil: Keywords\Keyword_Recoil.md
  - Keyword_Reduced: Keywords\Keyword_Reduced.md
  - Keyword_Secret: Keywords\Keyword_Secret.md
  - Keyword_Security: Keywords\Keyword_Security.md
  - Keyword_Security_Alert: Keywords\Keyword_Security_Alert.md
  - Keyword_Signature_Trick: Keywords\Keyword_Signature_Trick.md
  - Keyword_Skill_Bonus: Keywords\Keyword_Skill_Bonus.md
  - Keyword_Small_Item: Keywords\Keyword_Small_Item.md
  - Keyword_Social: Keywords\Keyword_Social.md
  - Keyword_Spray: Keywords\Keyword_Spray.md
  - Keyword_Spread: Keywords\Keyword_Spread.md
  - Keyword_Stability: Keywords\Keyword_Stability.md
  - Keyword_Stabilization_DL: Keywords\Keyword_Stabilization_DL.md
  - Keyword_Supplies: Keywords\Keyword_Supplies.md
  - Keyword_Surgical_Procedure: Keywords\Keyword_Surgical_Procedure.md
  - Keyword_Temporary: Keywords\Keyword_Temporary.md
  - Keyword_Threat: Keywords\Keyword_Threat.md
  - Keyword_Tools: Keywords\Keyword_Tools.md
  - Keyword_Trick: Keywords\Keyword_Trick.md
  - Keyword_Two_Handed_Grip: Keywords\Keyword_Two_Handed_Grip.md
  - Keyword_Two_Hands: Keywords\Keyword_Two_Hands.md
  - Keyword_Unarmed_Strike: Keywords\Keyword_Unarmed_Strike.md
  - Keyword_Upgraded: Keywords\Keyword_Upgraded.md
  - Keyword_Vehicle: Keywords\Keyword_Vehicle.md
  - Keyword_Vicinity: Keywords\Keyword_Vicinity.md
  - Keyword_Visible: Keywords\Keyword_Visible.md
  - Keyword_Visual: Keywords\Keyword_Visual.md
  - Keyword_Vocal: Keywords\Keyword_Vocal.md
  - Keyword_Weapon_Group: Keywords\Keyword_Weapon_Group.md
  - Keyword_Weapon_Types: Keywords\Keyword_Weapon_Types.md
  - Keyword_Wireless: Keywords\Keyword_Wireless.md
  - Keyword_Wits: Keywords\Keyword_Wits.md
- Making_a_Roll:
  - 2d10_Probability_Tables: Making_a_Roll\2d10_Probability_Tables.md
  - Adjusting_the_Difficulty_Level: Making_a_Roll\Adjusting_the_Difficulty_Level.md
  - Difficulty_Level: Making_a_Roll\Difficulty_Level.md
  - End_of_the_Action: Making_a_Roll\End_of_the_Action.md
  - Luck_Points: Making_a_Roll\Luck_Points.md
  - Making_a_Roll: Making_a_Roll\Making_a_Roll.md
  - Outcomes: Making_a_Roll\Outcomes.md
  - Roll_2d10: Making_a_Roll\Roll_2d10.md
  - When_to_Roll: Making_a_Roll\When_to_Roll.md
- Skills_and_Tricks:
  - Skill_Presence_Intimidate: Skills_and_Tricks\Skill_Presence_Intimidate.md
  - Skill_Presence_Persuade: Skills_and_Tricks\Skill_Presence_Persuade.md
  - Skills_and_Tricks: Skills_and_Tricks\Skills_and_Tricks.md
  - Skills_and_Tricks_List: Skills_and_Tricks\Skills_and_Tricks_List.md
  - Trick_Athletics_Acrobatic_Stunt: Skills_and_Tricks\Trick_Athletics_Acrobatic_Stunt.md
  - Trick_Athletics_Core_Athletic_Move: Skills_and_Tricks\Trick_Athletics_Core_Athletic_Move.md
  - Trick_Athletics_Core_Catch: Skills_and_Tricks\Trick_Athletics_Core_Catch.md
  - Trick_Athletics_Core_Sprint: Skills_and_Tricks\Trick_Athletics_Core_Sprint.md
  - Trick_Athletics_Core_Throw: Skills_and_Tricks\Trick_Athletics_Core_Throw.md
  - Trick_Brawl_Core_Forced_Move: Skills_and_Tricks\Trick_Brawl_Core_Forced_Move.md
  - Trick_Brawl_Core_Grapple: Skills_and_Tricks\Trick_Brawl_Core_Grapple.md
  - Trick_Brawl_Core_Unarmed_Strike: Skills_and_Tricks\Trick_Brawl_Core_Unarmed_Strike.md
  - Trick_Brawl_Silent_Takedown: Skills_and_Tricks\Trick_Brawl_Silent_Takedown.md
  - Trick_Culture_Core_City_Culture: Skills_and_Tricks\Trick_Culture_Core_City_Culture.md
  - Trick_Culture_Corporate_Culture: Skills_and_Tricks\Trick_Culture_Corporate_Culture.md
  - Trick_Culture_Milsec_Culture: Skills_and_Tricks\Trick_Culture_Milsec_Culture.md
  - Trick_Culture_Street_Culture: Skills_and_Tricks\Trick_Culture_Street_Culture.md
  - Trick_Culture_Underworld_Culture: Skills_and_Tricks\Trick_Culture_Underworld_Culture.md
  - Trick_Deception_Core_Bluff: Skills_and_Tricks\Trick_Deception_Core_Bluff.md
  - Trick_Deception_Core_Misdirect: Skills_and_Tricks\Trick_Deception_Core_Misdirect.md
  - Trick_Deception_Disguise: Skills_and_Tricks\Trick_Deception_Disguise.md
  - Trick_Deception_Forgery: Skills_and_Tricks\Trick_Deception_Forgery.md
  - Trick_Deception_Impersonate: Skills_and_Tricks\Trick_Deception_Impersonate.md
  - Trick_Drive_Core_Avoid_Crash: Skills_and_Tricks\Trick_Drive_Core_Avoid_Crash.md
  - Trick_Drive_Core_Chase: Skills_and_Tricks\Trick_Drive_Core_Chase.md
  - Trick_Drive_Core_Escape: Skills_and_Tricks\Trick_Drive_Core_Escape.md
  - Trick_Drive_Core_Sideswipe: Skills_and_Tricks\Trick_Drive_Core_Sideswipe.md
  - Trick_Drive_Driving_Stunt: Skills_and_Tricks\Trick_Drive_Driving_Stunt.md
  - Trick_Drive_Pit_Maneuver: Skills_and_Tricks\Trick_Drive_Pit_Maneuver.md
  - Trick_Firearms_Core_Burst_Fire: Skills_and_Tricks\Trick_Firearms_Core_Burst_Fire.md
  - Trick_Firearms_Core_Full_Auto: Skills_and_Tricks\Trick_Firearms_Core_Full_Auto.md
  - Trick_Firearms_Core_Single_Shot: Skills_and_Tricks\Trick_Firearms_Core_Single_Shot.md
  - Trick_Firearms_Crippling_Shot: Skills_and_Tricks\Trick_Firearms_Crippling_Shot.md
  - Trick_Firearms_Dual_Shot: Skills_and_Tricks\Trick_Firearms_Dual_Shot.md
  - Trick_Hacking_Core_Disable_Device: Skills_and_Tricks\Trick_Hacking_Core_Disable_Device.md
  - Trick_Hacking_Cybernetic_Hack: Skills_and_Tricks\Trick_Hacking_Cybernetic_Hack.md
  - Trick_Hacking_Droptrip: Skills_and_Tricks\Trick_Hacking_Droptrip.md
  - Trick_Hacking_Street_Hack: Skills_and_Tricks\Trick_Hacking_Street_Hack.md
  - Trick_Insight_Core_Read_Person: Skills_and_Tricks\Trick_Insight_Core_Read_Person.md
  - Trick_Insight_Core_Sense_Lies: Skills_and_Tricks\Trick_Insight_Core_Sense_Lies.md
  - Trick_Insight_Core_Size_Up_Opponent: Skills_and_Tricks\Trick_Insight_Core_Size_Up_Opponent.md
  - Trick_Insight_Dodge: Skills_and_Tricks\Trick_Insight_Dodge.md
  - Trick_Intimidate_Core_Coerce: Skills_and_Tricks\Trick_Intimidate_Core_Coerce.md
  - Trick_Intimidate_Core_Mock: Skills_and_Tricks\Trick_Intimidate_Core_Mock.md
  - Trick_Intimidate_Frighten: Skills_and_Tricks\Trick_Intimidate_Frighten.md
  - Trick_Intimidate_Shakedown: Skills_and_Tricks\Trick_Intimidate_Shakedown.md
  - Trick_Intimidate_Shred: Skills_and_Tricks\Trick_Intimidate_Shred.md
  - Trick_Medicine_Core_First_Aid: Skills_and_Tricks\Trick_Medicine_Core_First_Aid.md
  - Trick_Medicine_Core_Medical_Assessment: Skills_and_Tricks\Trick_Medicine_Core_Medical_Assessment.md
  - Trick_Medicine_Cybernetic_Installation: Skills_and_Tricks\Trick_Medicine_Cybernetic_Installation.md
  - Trick_Medicine_Surgery: Skills_and_Tricks\Trick_Medicine_Surgery.md
  - Trick_Melee_Core_Melee_Strike: Skills_and_Tricks\Trick_Melee_Core_Melee_Strike.md
  - Trick_Melee_Dazzling_Strike: Skills_and_Tricks\Trick_Melee_Dazzling_Strike.md
  - Trick_Melee_Finishing_Move: Skills_and_Tricks\Trick_Melee_Finishing_Move.md
  - Trick_Melee_Leaping_Strike: Skills_and_Tricks\Trick_Melee_Leaping_Strike.md
  - Trick_Perception_Core_Search: Skills_and_Tricks\Trick_Perception_Core_Search.md
  - Trick_Perception_Dead_Eye: Skills_and_Tricks\Trick_Perception_Dead_Eye.md
  - Trick_Perception_Overwatch: Skills_and_Tricks\Trick_Perception_Overwatch.md
  - Trick_Perception_Read_Lips: Skills_and_Tricks\Trick_Perception_Read_Lips.md
  - Trick_Persuade_Captivate: Skills_and_Tricks\Trick_Persuade_Captivate.md
  - Trick_Persuade_Core_Convince: Skills_and_Tricks\Trick_Persuade_Core_Convince.md
  - Trick_Persuade_Core_Haggle: Skills_and_Tricks\Trick_Persuade_Core_Haggle.md
  - Trick_Persuade_Entertain: Skills_and_Tricks\Trick_Persuade_Entertain.md
  - Trick_Piloting_Core_Deploy_Payload: Skills_and_Tricks\Trick_Piloting_Core_Deploy_Payload.md
  - Trick_Piloting_Core_Drone_Recon: Skills_and_Tricks\Trick_Piloting_Core_Drone_Recon.md
  - Trick_Piloting_Initiate_Countermeasures: Skills_and_Tricks\Trick_Piloting_Initiate_Countermeasures.md
  - Trick_Piloting_Manipulate_Object: Skills_and_Tricks\Trick_Piloting_Manipulate_Object.md
  - Trick_Piloting_Strafing_Run: Skills_and_Tricks\Trick_Piloting_Strafing_Run.md
  - Trick_Stealth_Close_Up_Magic: Skills_and_Tricks\Trick_Stealth_Close_Up_Magic.md
  - Trick_Stealth_Core_Sneak: Skills_and_Tricks\Trick_Stealth_Core_Sneak.md
  - Trick_Stealth_Disappear: Skills_and_Tricks\Trick_Stealth_Disappear.md
  - Trick_Stealth_Pickpocket: Skills_and_Tricks\Trick_Stealth_Pickpocket.md
  - Trick_Stealth_Shadow_Target: Skills_and_Tricks\Trick_Stealth_Shadow_Target.md
- Turns:
  - Round_Robin_the_Flow_of_the_Game: Turns\Round_Robin_the_Flow_of_the_Game.md
  - Turn_Etiquette: Turns\Turn_Etiquette.md
  - Turn_Length: Turns\Turn_Length.md
  - Turn_Order: Turns\Turn_Order.md
  - Types_of_Turns: Turns\Types_of_Turns.md
  - Your_Turn: Turns\Your_Turn.md
